version: '3.8'

services:
  php82-fpm-alpine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLATFORM: ${PLATFORM}
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: madebymode/php82-fpm-alpine:latest
    environment:
      HOST_ENV: development
      HOST_USER_UID: 1000
      HOST_USER_GID: 1000
