name: Create Releases

on:
  push:
    branches:
      - 'master'

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Create Releases
        run: |
          for DIR in */ ; do
            DIR=${DIR%*/}      # remove the trailing "/"
            if [[ -f "$DIR/.env" ]]; then
              set -a
              source $DIR/.env
              set +a
              TAG_NAME="php-${PHP_VERSION}"
              RELEASE_ID=$(gh release view $TAG_NAME --json id -q ".id")
              if [[ -z $RELEASE_ID ]]; then
                # Create GitHub release if it does not exist
                gh release create $TAG_NAME \
                  --title "PHP $PHP_VERSION release" \
                  --notes "Release of Docker image for PHP $PHP_VERSION"
              fi
            fi
          done
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
